### ISSUE TITLE
Add per-user responses to templates

### ISSUE THREAD

**Issue by terminalnode** [terminalnode/mrfreeze#36]
Not sure how best to implement this, but similarily to how it checks for the bot owner to do the FREEZE_OWNER response it would be neat if there were per-user responses for each template.

So the template file would have a section with something like:
```toml
[positive_user_exceptions]
 12345 = "I would never banish $fails! Ever!"
[negative_user_exceptions]
  67890 = "Yes, $fails sucks. Now they can suck in Antarctica!"
```
Where the numbers are the user's id.

We'd have to check for collisions though and some of the logic for fetching the right template might need a fixup. One idea would be to loop through these sections individually, build a list of exceptions and add a check for exception or fetch exception-method to the template engine. Lots of new code, but probably not very hard to do.
